environment:
  global:
    TOXENV: py

  matrix:
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python27

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -IU pip
  - python -m pip install -IU setuptools wheel tox

build: false

test_script:
  - python -m tox --skip-missing-interpreters=false

after_test:
  - python setup.py release bdist_wheel

artifacts:
  - path: dist\*.whl
    type: whl

branches:
  only:
    - master
    - /^.*\.x$/

cache:
  - '%LOCALAPPDATA%\pip\Cache'
