environment:
  global:
    TOXENV: py

  matrix:
    - PYTHON: C:\Python37-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python27

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U pip
  - python -m pip install -U setuptools wheel tox

build: false

test_script:
  - python -m tox --skip-missing-interpreters=false

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl
    type: whl

deploy:
  provider: S3
  access_key_id:
    secure: "KP/pEANcoiWbT6ie9cwmMseUN2Z/VZEmcN2kAlA8rdY="
  secret_access_key:
    secure: "kaYMEi5krUfR1pKRyXbuL7Lkxwrv6T6qwfhl0bE0BPqKCSOU1REx23OYz97UtAGq"
  bucket: pallets-wheels
  region: us-east-1
  folder: markupsafe

branches:
  only:
    - master
    - /^.*\.x$/

cache:
  - '%LOCALAPPDATA%\pip\Cache'
