environment:
  global:
    TOXENV: "py"

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python34-x64
    - PYTHON: C:\Python35
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64

init:
  - SET PATH=%PYTHON%;%PATH%

install:
  - python -m pip install -U pip setuptools wheel tox

build: off  # Not a C# project, build stuff at the test step instead.

test_script:
  - python -m tox

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl
    type: whl
