sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
install:
  - pip install tox
script:
  - tox -e py
notifications:
  email: false
  irc:
    channels:
      - chat.freenode.net#pocoo
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
